### PR TITLE
Add filtering options to get-collector

### PR DESCRIPTION
**Pull request by rickjuryxero**
I have added two simple filter options for simple use cases
- sourceSyncMode
- collectorType

and one advanced filter option where you can pass a hashtable of property / value pairs for other use cases (such as filtering by ephemeral, alive, osVer etc)

This simplifies interacting with get-collector as it means you can do filtering for most common use cases without resorting to extra | where ... clauses.

I have added examples of use to samples doc and some verbose logging for testing if your filtering is doing what you expected.

Example:
```
$c=Get-Collector -limit 10000 -Offset 0 -FilterProperties @{ "sourceSyncMode" = "UI"; "alive" = $false; "ephemeral" = $false } -Verbose                                                             
VERBOSE: GET https://api.us2.sumologic.com/api/v1/collectors?limit=10000&offset=0& with 0-byte payload
VERBOSE: received -byte response of content type application/json
VERBOSE: Content encoding: iso-8859-1
VERBOSE: Returned 4060 collectors before filtering
VERBOSE: filter on FilterProperties property: alive -eq False 
VERBOSE: filter on FilterProperties property: ephemeral -eq False 
VERBOSE: filter on FilterProperties property: sourceSyncMode -eq UI 
VERBOSE: There are 18 collectors after filtering
```

### CODE REVIEW

**Comment by bin3377** [comment]
@rickjuryxero the enhanced feature looks good. On concern is if using both `offset/limit` and filter(s), is that means the number of `limit` is actually the number before filtering? It's a little bit confuse.

**Comment by rickjuryxero** [comment]
@bin3377 I think sumo defaults to 1000 limit so if you have more than that you must always use -limit to a bigger number, as you must return every collector that exists before filtering them to a smaller subset by one of the properties. Otherwise you only get results if by chance the collectors you want are in the first batch of results. I agree it is a bit confusing!

**Comment by rickjuryxero** [comment]
@bin3377 I have improved readme and sample.ps1 based on your suggestion

**Comment by rickjuryxero** [comment]
@bin3377 do I need to make changes or can you merge this?

**Comment by bin3377** [comment]
@rickjuryxero Thank you for your suggestion! But as I commented above, adding parameters for filtering purpose to all parameter sets will cause logical conflictions. 

On the other side, the same result is easily got by pipeline the result of `Get-Collector` to `Where-Object`. For me, it at least has following advantages:
- It's intuitive way for PowerShell users
- Consistent for both `Get-Collector` and `Get-Source` so we don't need add similar patterns on both cmdlets
- User will explicit know they are getting all collector first and then filtering it locally. so they will not confused by getting one collector sometimes very fast but in some other cases very slow (since queried a large set then filter them out locally)
- User will not confused when getting an empty set with `-page`, `-limit` and `-filter`. Is that means there is no more result or is that just means all result in current page are filtered out?
- User can do more flexible query like `Where-Object {$_.collectorType - eq "Hosted" -or $_. alive}`

So I don't think this is a necessary change for current `Get-Collector` cmdlet.

**Pull request closed without merging**
